[package]
name = "pdf-handler"
version = "0.1.0"
authors = ["Christophe NÃ©raud <christophe.neraud@grenoble-inp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24.2"
regex = "1.4.2"
